on: push
jobs:
  knip:
    name: knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v4
      - run: pnpm install
      - run: pnpm run knip
